### ISSUE TITLE
is possible to resample a jack signal internally in the encoder?

### ISSUE THREAD

**Issue by allegfede** [Opendigitalradio/ODR-AudioEnc#10]
Hello. I had to run my jack audio server at 192KHz, because i need to feed the sound card with a software generated MPX which provides stereo and rds signals.

But now i cannot run ODR-audioEnc within the same jack server 'cause it accepts only 48KHZ sampling rate (am i wrong?).

Is there a way to resample signal from 48KHz from 192KHz in odr-audioenc?

Thanks.

PS: i got a similar problem with darkice for internet streaming but it provides an internal resampler (also liquidsoap provides internal resampler).

**Comment by allegfede** [comment]
i partially solved using this command:
odr-audioenc -l -v jack://dab_stranamore -L --audio-resampler=32000 -L --src-converter-type=0  -b $BITRATE -f -A --sbr -p 58 -P $fifo_file -o $DST

instead of the original:
odr-audioenc -l --jack=dab  -b $BITRATE -f -A --sbr -p 58 -P $fifo_file -o $DST

so now i use the internal resampler of vlc to scale my 192khz jack audio server to 32k

**Comment by mpbraendli** [comment]
Thanks for the workaround, I added it to the README.

**Comment by allegfede** [comment]
Thanks to you ;-)

Il mar 9 apr 2019, 07:26 Matthias P. Braendli <notifications@github.com> ha
scritto:
