### ISSUE TITLE
Compilation with --enable-gst fails

### ISSUE THREAD

**Issue by nickpiggott** [Opendigitalradio/ODR-AudioEnc#13]
**Environment**
* Debian Jessie
* All specified gstream1.0 libraries and plugins installed using apt
* ./configure --enable-vlc --enable-gst

**Problem**
Compilation fails with the error:

`src/GSTInput.cpp: In member function ‘virtual void GSTInput::prepare()’:
src/GSTInput.cpp:124:33: error: ‘GST_AUDIO_RESAMPLER_FILTER_MODE_FULL’ was not declared in this scope 
"sinc-filter-mode", GST_AUDIO_RESAMPLER_FILTER_MODE_FULL,
`

I couldn't find any files in the GStreamer libraries (/usr/include/gstreamer-1.0/gst) that defined that static value, although the GStreamer audioresample [documentation](https://gstreamer.freedesktop.org/documentation/audioresample/index.html?gi-language=c) suggests it should be defined.

**Workaround**
I commented out the explicit definition of sinc-filter-mode, which the documentation suggests defaults to " GST_AUDIO_RESAMPLER_FILTER_MODE_AUTO". Compilation then succeeded, and the GStreamer input to odr-audioenc worked apparently correctly.

**Comment by mpbraendli** [comment]
The GST version jessie includes is too old If you're able to do a simple patch that sets the filter mode if the GST version allows it I might take it, but I don't want to take too much time for jessie support.

**Comment by nickpiggott** [comment]
If I can find the time, I'll wrap that call in a 
#IFDEF 
and adjust it accordingly.

**Comment by mpbraendli** [comment]
I hope c9b1492 fixes that, I didn't try on jessie.
