### ISSUE TITLE
Drift compensation not recovering after 90sec of source disconnection.

### ISSUE THREAD

**Issue by salvaaod** [Opendigitalradio/ODR-AudioEnc#29]
OS: Ubuntu 20.04 LTS server.
odr-audioenc  3.4.0
Sample command:  odr-audioenc -D -v  http://stream.********.com:8000  -e tcp://*:9000

If connection with the server is lost, either the network is down or the server is down, the log starts to spit UUUUU if the server or the network disconnection is longer than 90 sec. down the encoding process will not resume after network connection or server recovery and the spiting of UUU will continue forever  having to restart the process manually. That makes the -D option unusable if your networks is not stable or if the servers you are getting the audio from have interruptions for one reason or another.

I have seen the same issue with -G (GST) but is not so easily reproduceable and happens more randomly, with the vlc decoder can be always reproduced.

**Comment by mpbraendli** [comment]
Hi, can you try the latest `next` ? I've implemented a check that should abort if there are underruns for 60s.

**Comment by salvaaod** [comment]
Yes, will do that and report results.

**Comment by salvaaod** [comment]
Old thread, just want to confirm that the issue is gone in last build, so you can close this.
