### ISSUE TITLE
PADencoder FiFo to RAM

### ISSUE THREAD

**Issue by MarkieV** [Opendigitalradio/ODR-AudioEnc#30]
I hope this is the right place for my question (google groups is closed?)

After a while I picked up mmbtools again and gone from version 2.xx to the latest, and I have to say that some things changed.
Especially sound quality has improved very! much.

In the 'old' days I had to make a FiFo between the Pad-encoder and the Audio-encoder, to prevent flash worn out (SD card on a Raspberry) I made this FiFo in RAM with /dev/shm
In the new version it is in /tmp, as I believe /tmp on a PI is also on the SD card.

Is there a way to change this? I did a little peek in the source code from the pad-encoder and saw some /tmp entrys can I simply
change this in /dev/shm? (and change this in audio-encoder also) and recompile again?

Grtzz  Mark

**Comment by mpbraendli** [comment]
Hello, newer versions use a socket, not a FIFO. Having the socket is /tmp isn't a problem, as the data doesn't actually go through the SD card.

Google groups had spam issues, and the admins aren't active anymore. The discussion group is now on https://groups.io/g/odr-mmbtools
