### ISSUE TITLE
mplayer snd-aloop example: Set format to s16le

### ISSUE THREAD

**Issue by MaPePeR** [Opendigitalradio/ODR-AudioEnc#5]
I had the problem, that i had to start my `odr-audioenc` before starting the `mplayer`, because it otherwise failed to set the sample format. I assumed that this is caused by `mplayer` setting the sample format to something else and alsa does not allow `odr-audioenc` to specify a different format later.

To fix that i added `-format s16le` to the `mplayer` command.

**Comment by mpbraendli** [comment]
Thanks! Added this remark to the README in commit 193ddda
